import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { AppbarMain } from "../components/appbarmain";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transacto",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="bg-gradient-to-r from-zinc-900 via-indigo-900 to-violet-500">
          <AppbarMain/>
          </div>
          
          {children}
        </body>
      </Providers>
      
    </html>
  );
}
