name: Build image and push

on: 
    pull_request:
        branches:
            - main
            - master

jobs: 
    build_and_deploy:
        name: build and deploy the project
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: prepare docker file
              run: cp ./apps/docker/Dockerfile.user ./Dockerfile

            - name: log-in to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build and push docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: dps1005/payment_user_app:latest

            - name: verify pushed image
              run: docker pull dps1005/payment_user_app:latest

            - name: push to aws EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USER}}
                key: ${{secrets.SSH_KEY}}
                script: |
                    sudo docker pull dps1005/payment_user_app:latest
                    sudo docker stop payment_user_app || true
                    sudo docker rm payment_user_app || true
                    sudo docker run -d --name payment_user_app -p 3005:3000 dps1005/payment_user_app:latest
